[package]
name = "rust_easy_todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
time = {version = "0.3.36", features = ["serde", "macros"]}
ratatui = "0.27.0" # possibly add serde flag for saving themes
crossterm = "0.27.0"